name: Proposal Research - Fail Test
on: [push]

jobs:
  research-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Try to Build (This will fail)
        run: |
          ./autogen.sh
          ./configure
          make
